<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <ReleaseOutputDir>..\..\Build-addons\SPT\user\mods\sgtlaggy-sharedweaponbuilds-fikaofflinecompat\</ReleaseOutputDir>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SPTarkov.Common" Version="4.0.0" />
    <PackageReference Include="SPTarkov.DI" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Reflection" Version="4.0.0" />
    <PackageReference Include="SPTarkov.Server.Core" Version="4.0.0" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="References\" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\SharedWeaponBuilds.Server\SharedWeaponBuilds.Server.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="FikaServer">
      <HintPath>..\..\References\FikaServer.dll</HintPath>
    </Reference>
  </ItemGroup>
  <Target Name="CleanUnwantedFiles" AfterTargets="Build">
    <ItemGroup>
      <UnwantedFiles Include="$(OutputPath)FikaServer.dll;$(OutputPath)SharedWeaponBuilds.Server.dll;$(OutputPath)*.pdb;$(OutputPath)*.deps.json;$(OutputPath)*.endpoints.json;$(OutputPath)*.runtimeconfig.*;$(OutputPath)*.staticwebassets.*;" />
    </ItemGroup>
    <Delete Files="@(UnwantedFiles)" />
  </Target>
  <Target Name="CopyBuildOutput" AfterTargets="CleanUnwantedFiles">
    <MakeDir Directories="$(ReleaseOutputDir)" />
    <ItemGroup>
      <RemainingFiles Include="$(OutputPath)**\*" />
      <WebAssets Include="$(ProjectDir)wwwroot\**\*.*" />
    </ItemGroup>
    <Copy SourceFiles="@(RemainingFiles)" DestinationFiles="@(RemainingFiles->'$(ReleaseOutputDir)%(RecursiveDir)%(Filename)%(Extension)')" />
    <Copy SourceFiles="@(WebAssets)" DestinationFiles="@(WebAssets->'$(ReleaseOutputDir)wwwroot\%(RecursiveDir)%(Filename)%(Extension)')" />
  </Target>
</Project>
